buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
siteStream:
  id: site-stream
  entityId: hybridSite
  fields:
    - favicon
    - logo
    - twitterHandle
    - facebookPageUrl
    - instagramHandle
    - linkedInUrl
    - pinterestUrl
    - tikTokUrl
    - youTubeChannelUrl
    - copyrightMessage
    - header
    - footer
  localization:
    locales:
      - en
      - es
      - fr
# authentication:
#   policyName: auth-policy
#   includePaths:
#     - /edit